aws:
  s3:
    download:
      url: https://%s.s3.amazonaws.com/%s
    storage:
      accessKey: ${AWS_S3_ACCESS_KEY:}
      secretKey: ${AWS_S3_SECRET_KEY:}
      region: ${AWS_S3_STORAGE_REGION:eu-north-1}
      bucket-name: ${AWS_S3_BUCKET_NAME:homebrew-packages}
      preSigned-url-ttl: ${AWS_S3_PRESIGNED_URL_TTL:10}
spring:
  app:
    url: http://localhost:8080/v1/uploadPackage
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USERNAME:mongoadmin}:${MONGO_DB_PASSWORD:root}@${MONGO_DB_HOST:localhost}:${MONGO_DB_PORT:27017}/admin


